# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07\x65xample\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"0\n\x13HelloWithAgeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"/\n\x11\x41\x64\x64NumbersRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"!\n\x12\x41\x64\x64NumbersResponse\x12\x0b\n\x03sum\x18\x01 \x01(\x05\" \n\x10TimeOfDayRequest\x12\x0c\n\x04hour\x18\x01 \x01(\x05\x32\x9d\x02\n\x0e\x45xampleService\x12\x39\n\x08SayHello\x12\x15.example.HelloRequest\x1a\x16.example.HelloResponse\x12G\n\x0fSayHelloWithAge\x12\x1c.example.HelloWithAgeRequest\x1a\x16.example.HelloResponse\x12\x45\n\nAddNumbers\x12\x1a.example.AddNumbersRequest\x1a\x1b.example.AddNumbersResponse\x12@\n\x0bGreetByTime\x12\x19.example.TimeOfDayRequest\x1a\x16.example.HelloResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=26
  _globals['_HELLOREQUEST']._serialized_end=54
  _globals['_HELLORESPONSE']._serialized_start=56
  _globals['_HELLORESPONSE']._serialized_end=88
  _globals['_HELLOWITHAGEREQUEST']._serialized_start=90
  _globals['_HELLOWITHAGEREQUEST']._serialized_end=138
  _globals['_ADDNUMBERSREQUEST']._serialized_start=140
  _globals['_ADDNUMBERSREQUEST']._serialized_end=187
  _globals['_ADDNUMBERSRESPONSE']._serialized_start=189
  _globals['_ADDNUMBERSRESPONSE']._serialized_end=222
  _globals['_TIMEOFDAYREQUEST']._serialized_start=224
  _globals['_TIMEOFDAYREQUEST']._serialized_end=256
  _globals['_EXAMPLESERVICE']._serialized_start=259
  _globals['_EXAMPLESERVICE']._serialized_end=544
# @@protoc_insertion_point(module_scope)
